<?php

namespace App\Http\Controllers\Api\Kpi;

use App\Http\Controllers\Controller;
use App\Models\KpiTarget;
use App\Services\AuditService;
use App\Services\KpiService;
use App\Support\KpiPeriod;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use InvalidArgumentException;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * FR-KPI-015: a downloadable performance report for one mission, or every
 * mission when {missionId} is "all" — targets, actuals, variance, the
 * previous period (trend), status and each quarter's report submission
 * compliance, attributed to the generating user with a timestamp. Ministry
 * HQ Director / Ministry PS / Acting PS, and the HRM&D Officer (API-001
 * Section 9; audit-logged, FR-KPI-011), see KpiPolicy::generateReport().
 *
 * No PDF/Excel library is installed and none may be added without approval,
 * so the report is a CSV (UTF-8 with a byte order mark, so spreadsheet
 * software opens it with the right characters).
 */
class KpiReportController extends Controller
{
    public function __construct(
        private readonly KpiService $kpiService,
        private readonly AuditService $auditService,
    ) {}

    public function show(Request $request, string $missionId): StreamedResponse
    {
        Gate::authorize('generateReport', KpiTarget::class);

        $label = (string) ($request->query('period') ?? $request->query('cycle_label', ''));
        abort_if(! KpiPeriod::isLabel($label), 422, 'Choose a quarter (Q1 2026) or half-year (H1 2026).');

        $user = $request->user();

        try {
            $report = $this->kpiService->buildMissionReport($user->ministry_id, $missionId === 'all' ? null : $missionId, $label, $user);
        } catch (InvalidArgumentException) {
            abort(404);
        }

        if ($user->role?->name === 'HRM&D Officer') {
            $this->auditService->record($user, 'kpi.report.generated', 'Ministry', $user->ministry_id, [
                'period' => $label,
                'mission_id' => $missionId,
            ]);
        }

        $scope = $missionId === 'all' ? 'all-missions' : str($report['missions'][0]['mission_name'] ?? 'mission')->slug();
        $filename = 'kpi-performance-'.$scope.'-'.str_replace(' ', '-', $label).'.csv';

        return response()->streamDownload(function () use ($report): void {
            $handle = fopen('php://output', 'w');
            fwrite($handle, "\xEF\xBB\xBF");

            $period = $report['period'];
            fputcsv($handle, ['TradeWatch KPI performance report']);
            fputcsv($handle, ['Period', "{$period['label']} ({$period['start']} to {$period['end']})", str_replace('_', ' ', $period['phase'])]);
            fputcsv($handle, ['Compared with', $report['previous_period']['label']]);
            fputcsv($handle, ['Status thresholds', 'On track at '.round($report['thresholds']['on_track'] * 100).'% of the target expected by now; at risk from '.round($report['thresholds']['at_risk'] * 100).'%']);
            fputcsv($handle, ['Generated by', $report['generated_by']['full_name'], $report['generated_at']]);
            fputcsv($handle, []);

            fputcsv($handle, ['Mission', 'City', 'Country', 'KPI', 'Target', 'Actual', 'Expected by now', 'Attainment %', 'Variance', 'Status', 'Previous period actual', 'Change', 'Change %', 'Target source', 'Quarters reported']);
            foreach ($report['missions'] as $mission) {
                foreach ($mission['kpis'] as $kpi) {
                    if (! $kpi['applicable']) {
                        continue;
                    }

                    fputcsv($handle, [
                        $mission['mission_name'],
                        $mission['city'],
                        $mission['host_country'],
                        $kpi['name'],
                        $kpi['target'] ?? '',
                        $kpi['actual'] ?? '',
                        $kpi['expected'] ?? '',
                        $kpi['attainment'] !== null ? round($kpi['attainment'] * 100, 1) : '',
                        $kpi['variance'] ?? '',
                        str_replace('_', ' ', $kpi['status']),
                        $kpi['previous_actual'] ?? '',
                        $kpi['change'] ?? '',
                        $kpi['change_pct'] !== null ? round($kpi['change_pct'] * 100, 1) : '',
                        $kpi['target_source'] ?? '',
                        $kpi['quarters_reported'].'/'.count($kpi['quarters']),
                    ]);
                }
            }

            fputcsv($handle, []);
            fputcsv($handle, ['Report submission compliance']);
            fputcsv($handle, ['Mission', 'Quarter', 'Status', 'Deadline', 'Submitted at']);
            foreach ($report['missions'] as $mission) {
                foreach ($mission['compliance'] as $quarter) {
                    fputcsv($handle, [
                        $mission['mission_name'],
                        $quarter['label'],
                        str_replace('_', ' ', $quarter['status']).($quarter['is_overdue'] ? ' (overdue)' : ''),
                        $quarter['deadline'],
                        $quarter['submitted_at'] ?? '',
                    ]);
                }
            }

            fclose($handle);
        }, $filename, ['Content-Type' => 'text/csv; charset=UTF-8']);
    }
}
