<?php

namespace Database\Seeders\Support;

use InvalidArgumentException;

/**
 * Hand-authored, real-world-grounded trade profile for each of the 17
 * TradeWatch missions (CLAUDE.md Section 8 Mission Roster). Feeds
 * ReportContentGenerator and the Demo*Seeder classes so every generated
 * report, alert, inquiry, directive, and KPI actual for a mission draws
 * from the same consistent, factual base rather than being independently
 * invented per record.
 *
 * `primary_attache` matches CLAUDE.md Section 8's existing named roster
 * (e.g. Geoffrey Odero / Washington) rather than inventing a new name for
 * that slot. `beats` has exactly 9 entries, one per report-bearing quarter
 * in chronological order (FY2024-25 Q1..Q4, FY2025-26 Q1..Q4, FY2026-27
 * Q1) — see DemoDataSeeder::REPORT_QUARTERS for the exact calendar mapping.
 * Each beat's `type` (trade_show | delegation | forum | compliance | other)
 * is reused by DemoKpiSeeder to keep the "Section 2 data" KPI actuals
 * (trade shows attended, delegations hosted, forums participated in)
 * numerically consistent with what the report narrative actually says.
 */
final class MissionTradeProfiles
{
    /**
     * @return array<string, array{
     *     tier: string,
     *     primary_attache: string,
     *     junior_attaches: array<int, string>,
     *     exports: array<int, string>,
     *     imports: array<int, string>,
     *     agreements: array<int, string>,
     *     orgs: array<int, string>,
     *     sectors: array<int, string>,
     *     challenge: ?string,
     *     beats: array<int, array{text: string, type: string}>,
     * }>
     */
    public static function all(): array
    {
        return [
            'Washington D.C.' => [
                'tier' => 'high',
                'primary_attache' => 'Geoffrey Odero',
                'junior_attaches' => ['Naomi Chepkirui'],
                'exports' => ['apparel and textiles (AGOA)', 'cut flowers', 'coffee', 'macadamia nuts', 'avocados'],
                'imports' => ['wheat', 'industrial machinery', 'aircraft parts', 'pharmaceuticals'],
                'agreements' => ['African Growth and Opportunity Act (AGOA)', 'US-Kenya Strategic Trade and Investment Partnership (STIP)'],
                'orgs' => ['Corporate Council on Africa', 'PVH Corp apparel sourcing desk', 'US Chamber of Commerce Africa desk', 'AGOA.info secretariat'],
                'sectors' => ['textiles and apparel', 'agriculture', 'ICT/BPO services'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Briefed the Corporate Council on Africa on Kenya\'s AGOA export performance ahead of the renewal advocacy push.', 'type' => 'forum'],
                    ['text' => 'Facilitated a 14-member Kenya apparel manufacturers delegation\'s buyer meetings with PVH Corp in New York.', 'type' => 'delegation'],
                    ['text' => 'Represented Kenya at the AGOA Forum preparatory sessions in Washington D.C.', 'type' => 'forum'],
                    ['text' => 'Resolved a tariff-classification query affecting a Kenyan cut-flowers consignment cleared through Miami.', 'type' => 'compliance'],
                    ['text' => 'Coordinated Congressional testimony materials for AGOA renewal advocacy ahead of the 2025 reauthorisation deadline.', 'type' => 'other'],
                    ['text' => 'Hosted a US-Kenya STIP working group session on customs and trade facilitation chapters.', 'type' => 'forum'],
                    ['text' => 'Accompanied a Kenyan macadamia and avocado exporters delegation to the Summer Fancy Food Show in New York.', 'type' => 'trade_show'],
                    ['text' => 'Supported resolution of a rules-of-origin verification request for a textiles shipment under AGOA scrutiny.', 'type' => 'compliance'],
                    ['text' => 'Currently coordinating a September 2026 Kenyan manufacturers delegation to the Magic Las Vegas apparel trade show.', 'type' => 'delegation'],
                ],
            ],
            'New Delhi' => [
                'tier' => 'high',
                'primary_attache' => 'Christine Muya',
                'junior_attaches' => ['Susan Nafula'],
                'exports' => ['soda ash', 'tea', 'pulses (re-export)', 'scrap metal'],
                'imports' => ['pharmaceuticals', 'industrial machinery', 'vehicles', 'petroleum products'],
                'agreements' => ['Kenya-India Joint Trade Committee', 'digital public infrastructure knowledge-exchange discussions'],
                'orgs' => ['Confederation of Indian Industry (CII)', 'Federation of Indian Chambers of Commerce and Industry (FICCI)', 'National Payments Corporation of India (NPCI)'],
                'sectors' => ['digital economy and fintech', 'pharmaceuticals', 'soda ash and industrial minerals'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Supported a soda ash quality-assurance visit for Gujarat-based glass manufacturers sourcing from Lake Magadi.', 'type' => 'other'],
                    ['text' => 'Facilitated Kenyan pulses re-exporters\' participation in the Delhi International Trade Fair.', 'type' => 'trade_show'],
                    ['text' => 'Opened exploratory talks with the National Payments Corporation of India on extending UPI-style instant payment rails to Kenyan retailers.', 'type' => 'other'],
                    ['text' => 'Hosted a 12-member Kenya Association of Manufacturers delegation on a market-scoping visit to Mumbai and Delhi.', 'type' => 'delegation'],
                    ['text' => 'Convened the Kenya-India Joint Trade Committee\'s digital economy working group inaugural session.', 'type' => 'forum'],
                    ['text' => 'Accompanied a Kenyan fintech delegation to the Global Fintech Fest in Mumbai.', 'type' => 'trade_show'],
                    ['text' => 'Negotiated resolution of a consignment-labelling dispute affecting Kenyan tea re-exports through Kolkata.', 'type' => 'compliance'],
                    ['text' => 'Hosted FICCI\'s Africa desk for a roundtable on pharmaceutical import tariff harmonisation.', 'type' => 'forum'],
                    ['text' => 'Currently finalising terms for a digital public infrastructure knowledge-exchange MOU ahead of the next Joint Trade Committee session.', 'type' => 'other'],
                ],
            ],
            'Kinshasa' => [
                'tier' => 'struggling',
                'primary_attache' => 'Peter Marengo',
                'junior_attaches' => [],
                'exports' => ['cement', 'plastics and packaging', 'processed foods', 'steel products', 'pharmaceuticals'],
                'imports' => ['cobalt and copper concentrates', 'timber'],
                'agreements' => ['COMESA', 'Great Lakes region trade facilitation initiatives'],
                'orgs' => ['Fédération des Entreprises du Congo (FEC)', 'COMESA Secretariat'],
                'sectors' => ['construction materials', 'consumer goods'],
                'challenge' => 'the security situation in eastern DRC, unreliable road and river logistics, and recurrent forex conversion delays affecting Kenyan traders\' repatriation of proceeds',
                'beats' => [
                    ['text' => 'Escorted a small cement-exporters delegation through the Kasumbalesa border crossing amid intermittent customs system outages.', 'type' => 'delegation'],
                    ['text' => 'Reported persistent forex conversion delays affecting Kenyan traders\' repatriation of proceeds from Kinshasa-based buyers.', 'type' => 'compliance'],
                    ['text' => 'Attended the Fédération des Entreprises du Congo\'s annual trade dialogue, arriving a day late after a cancelled connecting flight via Addis Ababa.', 'type' => 'forum'],
                    ['text' => 'Flagged a security-related suspension of road transport on the Goma corridor affecting three pending Kenyan steel-product shipments.', 'type' => 'compliance'],
                    ['text' => 'Supported a COMESA-facilitated trade facilitation workshop on the one-stop border post at Kasumbalesa.', 'type' => 'forum'],
                    ['text' => 'Hosted a delayed visit from a Nairobi-based plastics manufacturer scouting Kinshasa distribution partners.', 'type' => 'delegation'],
                    ['text' => 'Continued to monitor an unresolved customs valuation dispute affecting a Kenyan pharmaceuticals consignment held at Matadi port.', 'type' => 'compliance'],
                    ['text' => 'Coordinated with the Kenya High Commission on contingency logistics after renewed insecurity disrupted the Kinshasa-Lubumbashi trade route.', 'type' => 'other'],
                    ['text' => 'Currently reassessing the mission\'s transport-security contingency plan following the latest advisory from the Regional Security Office.', 'type' => 'other'],
                ],
            ],
            'Arusha' => [
                'tier' => 'struggling',
                'primary_attache' => 'Malvin Mulama',
                'junior_attaches' => [],
                'exports' => ['manufactured consumer goods', 'petroleum re-exports', 'plastics'],
                'imports' => ['gemstones (tanzanite)', 'agricultural produce'],
                'agreements' => ['EAC Common Market Protocol', 'EAC Customs Union'],
                'orgs' => ['EAC Secretariat', 'Tanzania Chamber of Commerce, Industry and Agriculture'],
                'sectors' => ['EAC regional integration', 'non-tariff barrier monitoring'],
                'challenge' => 'a single-officer post that must simultaneously cover EAC Secretariat liaison duties and bilateral trader casework, with recurring non-tariff barrier disputes at Namanga taking months to resolve',
                'beats' => [
                    ['text' => 'Attended the EAC Secretariat\'s Sectoral Council on Trade, raising Kenya\'s concerns over a new Tanzanian maize import levy.', 'type' => 'forum'],
                    ['text' => 'Logged a non-tariff barrier complaint from a Kenyan agro-processor over inconsistent weighbridge inspections at Namanga.', 'type' => 'compliance'],
                    ['text' => 'Represented Kenya at the EAC Business Council\'s regional trade facilitation forum, the mission\'s sole delegate given current staffing.', 'type' => 'forum'],
                    ['text' => 'Followed up on the still-unresolved Namanga weighbridge complaint, now four months outstanding.', 'type' => 'compliance'],
                    ['text' => 'Supported the EAC Secretariat\'s review of the Common External Tariff\'s fifth band ahead of ratification.', 'type' => 'forum'],
                    ['text' => 'Hosted a small delegation from the Kenya National Chamber of Commerce scoping EAC market-access opportunities, run single-handedly during a colleague\'s leave.', 'type' => 'delegation'],
                    ['text' => 'Escalated the Namanga weighbridge dispute to the EAC Secretariat\'s non-tariff barriers online reporting mechanism after continued delay.', 'type' => 'compliance'],
                    ['text' => 'Attended the EAC Council of Ministers\' pre-summit trade session in Arusha.', 'type' => 'forum'],
                    ['text' => 'Currently preparing the mission\'s submission to the EAC\'s 2026 non-tariff barriers time-bound elimination review.', 'type' => 'other'],
                ],
            ],
            'London' => [
                'tier' => 'high',
                'primary_attache' => 'Purity Samanthe',
                'junior_attaches' => ['Daniel Kiptoo'],
                'exports' => ['tea', 'cut flowers', 'coffee', 'avocados', 'fresh vegetables'],
                'imports' => ['industrial machinery', 'pharmaceuticals', 'used vehicles', 'whisky'],
                'agreements' => ['UK-Kenya Economic Partnership Agreement (EPA)'],
                'orgs' => ['Fairtrade Foundation', 'Tesco and Sainsbury\'s fresh produce buying teams', 'James Finlay (Kenya)', 'Williamson Tea', 'British Kenya Chamber of Commerce'],
                'sectors' => ['tea', 'horticulture (flowers and vegetables)', 'coffee'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Hosted a Fairtrade Foundation roundtable on smallholder tea premiums ahead of the EPA\'s fourth anniversary review.', 'type' => 'forum'],
                    ['text' => 'Facilitated three Kenyan flower exporters\' stands at a London horticulture trade showcase.', 'type' => 'trade_show'],
                    ['text' => 'Supported James Finlay (Kenya) and Williamson Tea\'s joint presentation to UK blenders on Mombasa auction quality trends.', 'type' => 'forum'],
                    ['text' => 'Hosted a 9-member Kenya horticulture delegation\'s meetings with Tesco and Sainsbury\'s fresh produce buying teams.', 'type' => 'delegation'],
                    ['text' => 'Convened a UK-Kenya EPA utilisation review with the Department for Business and Trade, identifying under-used tariff lines in processed foods.', 'type' => 'forum'],
                    ['text' => 'Accompanied a Kenyan avocado exporters delegation to the London Produce Show.', 'type' => 'trade_show'],
                    ['text' => 'Resolved a temporary customs documentation mismatch affecting a coffee consignment cleared through Tilbury port.', 'type' => 'compliance'],
                    ['text' => 'Hosted the British Kenya Chamber of Commerce\'s annual trade and investment dinner.', 'type' => 'forum'],
                    ['text' => 'Currently coordinating logistics for a September 2026 Kenyan agri-tech delegation visiting UK vertical-farming operators.', 'type' => 'delegation'],
                ],
            ],
            'Lusaka' => [
                'tier' => 'struggling',
                'primary_attache' => 'Caroline Chore',
                'junior_attaches' => [],
                'exports' => ['manufactured consumer goods', 'petroleum products', 'plastics', 'pharmaceuticals'],
                'imports' => ['copper products', 'cotton'],
                'agreements' => ['COMESA', 'COMESA-SADC-EAC Tripartite Free Trade Area'],
                'orgs' => ['Zambia Association of Chambers of Commerce and Industry (ZACCI)', 'COMESA Secretariat'],
                'sectors' => ['consumer goods', 'COMESA tripartite coordination'],
                'challenge' => 'a single-officer post carrying both bilateral casework and COMESA Secretariat liaison duties, which has left a recurring backlog of trader payment-dispute cases',
                'beats' => [
                    ['text' => 'Attended the COMESA Secretariat\'s trade facilitation committee, based just across town from the mission.', 'type' => 'forum'],
                    ['text' => 'Supported a small delegation of Kenyan plastics manufacturers scouting Zambian distributors, delayed a week by a vehicle breakdown en route to Ndola.', 'type' => 'delegation'],
                    ['text' => 'Logged a payment-delay complaint from a Kenyan pharmaceuticals supplier awaiting settlement from a Lusaka distributor.', 'type' => 'compliance'],
                    ['text' => 'Represented Kenya at the Zambia International Trade Fair in Ndola.', 'type' => 'trade_show'],
                    ['text' => 'Followed up on the still-outstanding pharmaceuticals payment dispute, now under COMESA\'s trade remedies desk.', 'type' => 'compliance'],
                    ['text' => 'Hosted the Zambia Association of Chambers of Commerce and Industry for a briefing on COMESA rules-of-origin documentation.', 'type' => 'forum'],
                    ['text' => 'Supported a Kenyan consumer-goods delegation\'s market entry meetings in Lusaka, submitted late due to a backlog in the mission\'s single-officer schedule.', 'type' => 'delegation'],
                    ['text' => 'Attended the COMESA-SADC-EAC Tripartite FTA technical working group session on tariff offer harmonisation.', 'type' => 'forum'],
                    ['text' => 'Currently clearing a backlog of three pending trader complaints inherited from the prior reporting period.', 'type' => 'other'],
                ],
            ],
            'Berlin' => [
                'tier' => 'high',
                'primary_attache' => 'Washington Mijele',
                'junior_attaches' => [],
                'exports' => ['coffee', 'cut flowers', 'tea', 'avocados'],
                'imports' => ['industrial machinery', 'automotive parts', 'chemicals', 'pharmaceuticals'],
                'agreements' => ['EU-EAC Economic Partnership Agreement', 'EU Deforestation Regulation (EUDR) compliance framework'],
                'orgs' => ['German Coffee Association', 'GIZ (German development agency)', 'Afrika-Verein der deutschen Wirtschaft'],
                'sectors' => ['coffee', 'horticulture', 'EUDR compliance'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Hosted a German Coffee Association delegation touring Mount Kenya region coffee cooperatives\' EUDR traceability systems.', 'type' => 'forum'],
                    ['text' => 'Facilitated three Kenyan coffee roasters\' participation in the Hamburg coffee trade exchange.', 'type' => 'trade_show'],
                    ['text' => 'Briefed exporters on the EU Deforestation Regulation\'s revised compliance timeline and geolocation data requirements.', 'type' => 'compliance'],
                    ['text' => 'Supported a GIZ-facilitated delegation of German horticultural technology firms visiting Naivasha flower farms.', 'type' => 'delegation'],
                    ['text' => 'Convened a briefing with the Afrika-Verein der deutschen Wirtschaft on EU-EAC EPA tariff-line utilisation for processed avocado products.', 'type' => 'forum'],
                    ['text' => 'Accompanied a Kenyan avocado and cut-flower delegation to Fruit Logistica preparatory meetings in Berlin.', 'type' => 'trade_show'],
                    ['text' => 'Resolved a documentation query on EUDR geolocation data for a coffee shipment cleared through Hamburg port.', 'type' => 'compliance'],
                    ['text' => 'Hosted a roundtable with German machinery exporters interested in Kenya\'s coffee-processing modernisation programme.', 'type' => 'forum'],
                    ['text' => 'Currently finalising EUDR compliance documentation templates for distribution to Kenyan coffee cooperatives ahead of the 2026/27 harvest.', 'type' => 'other'],
                ],
            ],
            'Pretoria' => [
                'tier' => 'average',
                'primary_attache' => 'Ryan Injendi',
                'junior_attaches' => [],
                'exports' => ['tea', 'coffee', 'textiles', 'processed foods'],
                'imports' => ['mining equipment', 'vehicles', 'industrial machinery', 'chemicals'],
                'agreements' => ['COMESA-SADC-EAC Tripartite Free Trade Area', 'African Continental Free Trade Area (AfCFTA)'],
                'orgs' => ['South African Chamber of Commerce and Industry', 'Proudly South African'],
                'sectors' => ['mining equipment imports', 'manufactured exports'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Hosted a Kenya Association of Manufacturers delegation\'s meetings with South African mining-equipment suppliers.', 'type' => 'delegation'],
                    ['text' => 'Attended the Proudly South African trade exhibition, showcasing Kenyan tea and processed foods.', 'type' => 'trade_show'],
                    ['text' => 'Logged a customs classification query affecting a Kenyan textiles consignment cleared through Durban port.', 'type' => 'compliance'],
                    ['text' => 'Supported the Tripartite Free Trade Area\'s technical review of Kenya-South Africa tariff offers.', 'type' => 'forum'],
                    ['text' => 'Hosted a South African Chamber of Commerce roundtable on AfCFTA rules-of-origin certification for Kenyan exporters.', 'type' => 'forum'],
                    ['text' => 'Facilitated a mining-equipment sourcing delegation from a Nairobi-based construction firm visiting Johannesburg suppliers.', 'type' => 'delegation'],
                    ['text' => 'Attended the Mining Indaba\'s Africa trade sidelines discussions on equipment import facilitation.', 'type' => 'trade_show'],
                    ['text' => 'Resolved a delayed VAT refund query for a Kenyan exporter registered under South Africa\'s customs regime.', 'type' => 'compliance'],
                    ['text' => 'Currently coordinating a September 2026 Kenyan agro-processing delegation\'s visit to Durban\'s export processing zone.', 'type' => 'delegation'],
                ],
            ],
            'Accra' => [
                'tier' => 'high',
                'primary_attache' => 'George Dinda',
                'junior_attaches' => [],
                'exports' => ['tea', 'coffee', 'textiles', 'plastics and packaging'],
                'imports' => ['cocoa-sector by-products', 'gold-sector equipment'],
                'agreements' => ['African Continental Free Trade Area (AfCFTA)', 'AfCFTA Guided Trade Initiative'],
                'orgs' => ['AfCFTA Secretariat', 'Ghana Union of Traders Association', 'Association of Ghana Industries'],
                'sectors' => ['AfCFTA implementation', 'intra-Africa trade facilitation'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Hosted a briefing with the AfCFTA Secretariat on the Guided Trade Initiative\'s pilot product list for Kenyan tea and coffee.', 'type' => 'forum'],
                    ['text' => 'Facilitated a Kenyan agro-processors delegation\'s participation in the Ghana International Trade Fair.', 'type' => 'trade_show'],
                    ['text' => 'Supported the first AfCFTA Guided Trade Initiative shipment of Kenyan tea cleared under preferential tariff treatment.', 'type' => 'compliance'],
                    ['text' => 'Reactivated the dormant Ghana-Kenya Business Council with a joint session hosted at the mission.', 'type' => 'forum'],
                    ['text' => 'Hosted the Association of Ghana Industries for a roundtable on AfCFTA digital trade protocol implications for Kenyan exporters.', 'type' => 'forum'],
                    ['text' => 'Accompanied a Kenyan plastics and packaging delegation to the AfCFTA Business Forum in Accra.', 'type' => 'delegation'],
                    ['text' => 'Resolved a rules-of-origin certification delay affecting a Kenyan textiles consignment under the Guided Trade Initiative.', 'type' => 'compliance'],
                    ['text' => 'Facilitated a second cohort of Kenyan exporters\' onboarding onto the AfCFTA Guided Trade Initiative product list.', 'type' => 'other'],
                    ['text' => 'Currently coordinating with the AfCFTA Secretariat on expanding the Guided Trade Initiative\'s product list to include Kenyan avocados.', 'type' => 'other'],
                ],
            ],
            'Cairo' => [
                'tier' => 'average',
                'primary_attache' => 'Tobias Ong\'any',
                'junior_attaches' => [],
                'exports' => ['tea', 'coffee', 'macadamia nuts', 'horticultural produce'],
                'imports' => ['fertilisers', 'textiles', 'petrochemicals', 'construction materials'],
                'agreements' => ['COMESA', 'Suez Canal logistics corridor cooperation'],
                'orgs' => ['Egyptian Federation of Chambers of Commerce', 'Suez Canal Authority'],
                'sectors' => ['logistics and Suez Canal corridor', 'fertiliser imports'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Hosted a briefing on Suez Canal Authority transit-fee changes affecting Kenyan cargo routed to European markets.', 'type' => 'forum'],
                    ['text' => 'Facilitated a Kenyan fertiliser-importers delegation\'s meetings with Egyptian petrochemical suppliers.', 'type' => 'delegation'],
                    ['text' => 'Attended the Egyptian Federation of Chambers of Commerce\'s regional trade dialogue on COMESA tariff harmonisation.', 'type' => 'forum'],
                    ['text' => 'Resolved a phytosanitary documentation query affecting a Kenyan avocado consignment transiting Alexandria port.', 'type' => 'compliance'],
                    ['text' => 'Supported a Kenyan construction-materials delegation scouting Egyptian cement and steel suppliers.', 'type' => 'delegation'],
                    ['text' => 'Facilitated Kenyan tea exporters\' participation in the Cairo International Fair.', 'type' => 'trade_show'],
                    ['text' => 'Logged a shipping-schedule disruption affecting three Kenyan consignments transiting the Suez Canal during regional maritime security incidents.', 'type' => 'compliance'],
                    ['text' => 'Hosted a COMESA customs modernisation workshop with Egyptian counterparts.', 'type' => 'forum'],
                    ['text' => 'Currently monitoring Suez Canal transit conditions and their effect on Kenyan exporters\' shipping cost projections for the new season.', 'type' => 'other'],
                ],
            ],
            'Jakarta' => [
                'tier' => 'average',
                'primary_attache' => 'Maureen Abungu',
                'junior_attaches' => [],
                'exports' => ['tea', 'coffee', 'macadamia nuts', 'pyrethrum extract'],
                'imports' => ['palm oil', 'textiles', 'electronics'],
                'agreements' => ['Kenya-Indonesia Joint Trade Committee'],
                'orgs' => ['Indonesian Chamber of Commerce and Industry (KADIN)', 'Indonesia Palm Oil Association'],
                'sectors' => ['edible oils market study', 'tea'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Attended the Indonesian Chamber of Commerce (KADIN) trade dialogue on palm oil and competing edible oils market dynamics.', 'type' => 'forum'],
                    ['text' => 'Facilitated a Kenyan tea exporters delegation\'s meetings with Jakarta-based blenders.', 'type' => 'delegation'],
                    ['text' => 'Commissioned a market study comparing Indonesian palm oil imports against Kenya\'s domestic edible-oils sourcing strategy.', 'type' => 'other'],
                    ['text' => 'Resolved a labelling-standard query affecting a Kenyan macadamia consignment cleared through Tanjung Priok port.', 'type' => 'compliance'],
                    ['text' => 'Hosted a Kenya-Indonesia Joint Trade Committee preparatory session on pyrethrum extract market access.', 'type' => 'forum'],
                    ['text' => 'Facilitated Kenyan coffee exporters\' participation in a Jakarta specialty-coffee trade showcase.', 'type' => 'trade_show'],
                    ['text' => 'Followed up on the palm-oil market study\'s findings with a briefing to Nairobi-based edible-oils processors.', 'type' => 'other'],
                    ['text' => 'Supported an Indonesia Palm Oil Association delegation\'s exploratory visit to Kenyan edible-oils processing facilities.', 'type' => 'delegation'],
                    ['text' => 'Currently preparing for the next Kenya-Indonesia Joint Trade Committee session, tentatively scheduled for late 2026.', 'type' => 'other'],
                ],
            ],
            'Beijing' => [
                'tier' => 'high',
                'primary_attache' => 'Geoffrey Kimani',
                'junior_attaches' => ['Esther Wanjiru', 'Kevin Otieno'],
                'exports' => ['avocados', 'tea', 'macadamia nuts', 'hides and skins'],
                'imports' => ['industrial machinery', 'electronics', 'construction materials', 'textiles'],
                'agreements' => ['Kenya-China Avocado Phytosanitary Protocol', 'Belt and Road Initiative (BRI) infrastructure cooperation'],
                'orgs' => ['General Administration of Customs China (GACC)', 'China Chamber of Commerce for Import and Export of Foodstuffs', 'China-Africa Trade Expo (Changsha)'],
                'sectors' => ['avocado market access', 'macadamia nuts', 'BRI infrastructure cooperation'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Hosted a GACC delegation for a pre-shipment audit of three new avocado packhouses in Murang\'a and Nakuru ahead of the 2024/25 export season.', 'type' => 'other'],
                    ['text' => 'Facilitated the first direct avocado consignment through the new Beijing-Guangzhou cold-chain corridor.', 'type' => 'other'],
                    ['text' => 'Represented Kenya at the China-Africa Trade Expo in Changsha, securing three new macadamia buyer introductions.', 'type' => 'trade_show'],
                    ['text' => 'Supported KEPHIS in resolving a phytosanitary interception on a tea consignment at Shanghai port.', 'type' => 'compliance'],
                    ['text' => 'Briefed visiting Kenyan avocado exporters on GACC\'s revised cold-treatment protocol ahead of the 2025/26 season.', 'type' => 'other'],
                    ['text' => 'Coordinated a Kenyan manufacturing delegation\'s visit to Guangzhou\'s Canton Fair, focused on light-industrial machinery sourcing.', 'type' => 'delegation'],
                    ['text' => 'Followed up on a Belt and Road-linked feasibility study for a Mombasa-Nairobi logistics upgrade with China Road and Bridge Corporation.', 'type' => 'other'],
                    ['text' => 'Hosted a macadamia quality-standards workshop with the China Chamber of Commerce for Import and Export of Foodstuffs.', 'type' => 'forum'],
                    ['text' => 'Currently coordinating GACC\'s mid-season avocado audit visit scheduled for September 2026.', 'type' => 'other'],
                ],
            ],
            'Dubai' => [
                'tier' => 'average',
                'primary_attache' => 'Alfred Abuko',
                'junior_attaches' => ['Hassan Abdi'],
                'exports' => ['tea (re-export hub)', 'coffee', 'horticultural produce'],
                'imports' => ['petroleum products', 'industrial machinery', 'electronics', 'gold'],
                'agreements' => ['draft Kenya-UAE bilateral labour agreement', 'COMESA-GCC trade dialogue'],
                'orgs' => ['Dubai Chamber of Commerce', 'DP World', 'Dubai Multi Commodities Centre', 'Kenya diaspora labour welfare desk'],
                'sectors' => ['labour migration agreements', 'tea re-export logistics', 'gold trade'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Hosted preliminary talks with the UAE Ministry of Human Resources and Emiratisation on a bilateral labour agreement protecting Kenyan domestic and skilled workers.', 'type' => 'forum'],
                    ['text' => 'Facilitated a Kenyan tea re-export delegation\'s meetings with Dubai Multi Commodities Centre traders.', 'type' => 'delegation'],
                    ['text' => 'Logged a wage-dispute case referred by the Kenya diaspora labour welfare desk for three domestic workers, referred to UAE labour authorities for resolution.', 'type' => 'compliance'],
                    ['text' => 'Supported DP World\'s briefing on expanded logistics capacity for Kenyan cargo transiting Jebel Ali port.', 'type' => 'forum'],
                    ['text' => 'Advanced the draft Kenya-UAE bilateral labour agreement to a second round of technical negotiations.', 'type' => 'other'],
                    ['text' => 'Facilitated a Kenyan gold and jewellery-sector delegation\'s participation in a Dubai Multi Commodities Centre trade showcase.', 'type' => 'trade_show'],
                    ['text' => 'Resolved a documentation dispute delaying accreditation of a new Kenyan recruitment agency under the draft labour agreement\'s vetting framework.', 'type' => 'compliance'],
                    ['text' => 'Hosted the Dubai Chamber of Commerce for a briefing on COMESA-GCC trade dialogue prospects.', 'type' => 'forum'],
                    ['text' => 'Currently awaiting UAE Cabinet-level sign-off on the finalised bilateral labour agreement text.', 'type' => 'other'],
                ],
            ],
            'Islamabad' => [
                'tier' => 'struggling',
                'primary_attache' => 'Fatuma Bonaya',
                'junior_attaches' => [],
                'exports' => ['tea', 'coffee', 'pyrethrum extract'],
                'imports' => ['rice', 'textiles', 'sports goods', 'surgical instruments'],
                'agreements' => ['Kenya-Pakistan Joint Trade Committee'],
                'orgs' => ['Pakistan Tea Association', 'Federation of Pakistan Chambers of Commerce and Industry (FPCCI)'],
                'sectors' => ['tea (Kenya\'s largest single export market by volume)', 'rice imports'],
                'challenge' => 'recurring travel-security advisories restricting movement to Karachi (Kenya\'s tea trade actually clears there, not Islamabad), and a small, under-resourced single-officer post',
                'beats' => [
                    ['text' => 'Attended the Pakistan Tea Association\'s annual outlook briefing, Kenya\'s single largest tea export market by volume.', 'type' => 'forum'],
                    ['text' => 'Logged a quality-grading dispute affecting a Kenyan tea consignment at Karachi port, travel to the port delayed by a regional security advisory.', 'type' => 'compliance'],
                    ['text' => 'Supported a smaller-than-planned Kenyan tea exporters delegation, two members having withdrawn over travel-advisory concerns.', 'type' => 'delegation'],
                    ['text' => 'Followed up on the Karachi tea-grading dispute, still unresolved after the prior quarter\'s advisory-related delays.', 'type' => 'compliance'],
                    ['text' => 'Attended the Federation of Pakistan Chambers of Commerce and Industry\'s Kenya-Pakistan Joint Trade Committee session, held virtually due to continued travel restrictions.', 'type' => 'forum'],
                    ['text' => 'Facilitated a rice-importers delegation from Nairobi\'s grain trading houses meeting Karachi suppliers by video conference.', 'type' => 'delegation'],
                    ['text' => 'Resolved the long-outstanding Karachi tea-grading dispute following escalation through the Pakistan Tea Association.', 'type' => 'compliance'],
                    ['text' => 'Hosted a limited in-person session with Pakistan Tea Association representatives after the security advisory was partially eased.', 'type' => 'forum'],
                    ['text' => 'Currently reassessing the mission\'s travel-security protocol ahead of the 2026/27 tea season\'s peak shipping period.', 'type' => 'other'],
                ],
            ],
            'Brasilia' => [
                'tier' => 'struggling',
                'primary_attache' => 'Reagan Mwanyngnu',
                'junior_attaches' => [],
                'exports' => ['tea', 'coffee', 'cut flowers (nascent)', 'macadamia nuts'],
                'imports' => ['soy products', 'aircraft', 'sugar', 'ethanol'],
                'agreements' => ['Kenya-Brazil agri-tech cooperation MOU (in negotiation)'],
                'orgs' => ['Brazilian Confederation of Agriculture and Livestock (CNA)', 'EMBRAPA (Brazilian Agricultural Research Corporation)'],
                'sectors' => ['agri-tech cooperation', 'soy import monitoring'],
                'challenge' => 'a significant Portuguese-language barrier, the roughly 1,000km distance between Brasilia and the Sao Paulo commercial hub where most trade actually clears, and a single-officer post',
                'beats' => [
                    ['text' => 'Attended a Brazilian Confederation of Agriculture and Livestock (CNA) briefing on soy import logistics, conducted with translation support given the mission\'s limited Portuguese-language capacity.', 'type' => 'forum'],
                    ['text' => 'Logged a shipping-documentation delay affecting a Kenyan cut-flowers trial consignment routed through Sao Paulo, the mission\'s nearest commercial hub some 1,000km from Brasilia.', 'type' => 'compliance'],
                    ['text' => 'Supported early-stage talks with EMBRAPA on an agri-tech cooperation MOU for drought-resistant seed research.', 'type' => 'forum'],
                    ['text' => 'Followed up on the Sao Paulo flower-consignment documentation delay, resolved after a three-month backlog.', 'type' => 'compliance'],
                    ['text' => 'Hosted a small Kenyan coffee-sector delegation\'s introductory meetings with Brazilian agri-tech firms, arranged around the mission\'s single-officer travel constraints.', 'type' => 'delegation'],
                    ['text' => 'Advanced the EMBRAPA agri-tech cooperation MOU to a working draft, translation review still pending.', 'type' => 'other'],
                    ['text' => 'Attended Brazil\'s agribusiness trade fair in Sao Paulo, representing Kenya\'s macadamia sector.', 'type' => 'trade_show'],
                    ['text' => 'Resolved a labelling-standard query on a Kenyan tea trial shipment cleared through Santos port.', 'type' => 'compliance'],
                    ['text' => 'Currently awaiting a Portuguese-language legal review of the EMBRAPA MOU draft before it can be forwarded to Nairobi for approval.', 'type' => 'other'],
                ],
            ],
            'Kampala' => [
                'tier' => 'average',
                'primary_attache' => 'Evaline Kuyu',
                'junior_attaches' => [],
                'exports' => ['manufactured goods', 'plastics', 'pharmaceuticals', 'petroleum re-exports', 'cement'],
                'imports' => ['agricultural produce', 'fish', 'tobacco'],
                'agreements' => ['EAC Customs Union', 'Malaba/Busia One-Stop Border Post'],
                'orgs' => ['Uganda National Chamber of Commerce and Industry', 'EAC Secretariat liaison desk'],
                'sectors' => ['EAC trade facilitation', 'border post efficiency', 'non-tariff barriers'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Hosted a briefing on the Malaba One-Stop Border Post\'s clearance-time improvements for Kenyan cargo.', 'type' => 'forum'],
                    ['text' => 'Facilitated a Kenyan cement and construction-materials delegation\'s meetings with Ugandan distributors.', 'type' => 'delegation'],
                    ['text' => 'Logged a non-tariff barrier complaint over inconsistent phytosanitary checks at the Busia border post.', 'type' => 'compliance'],
                    ['text' => 'Attended the Uganda National Chamber of Commerce\'s EAC trade facilitation dialogue.', 'type' => 'forum'],
                    ['text' => 'Supported resolution of the Busia phytosanitary complaint through the EAC\'s non-tariff barriers mechanism.', 'type' => 'compliance'],
                    ['text' => 'Facilitated Kenyan pharmaceuticals exporters\' participation in the Kampala International Trade Fair.', 'type' => 'trade_show'],
                    ['text' => 'Hosted a Kenyan petroleum-products delegation\'s meetings with Uganda\'s downstream distributors.', 'type' => 'delegation'],
                    ['text' => 'Attended a joint Kenya-Uganda review of Malaba/Busia border post digitisation progress.', 'type' => 'forum'],
                    ['text' => 'Currently coordinating logistics for a September 2026 Kenyan manufacturers delegation visiting Kampala\'s industrial park developments.', 'type' => 'delegation'],
                ],
            ],
            'Addis Ababa' => [
                'tier' => 'average',
                'primary_attache' => 'Brian Ndambuki',
                'junior_attaches' => [],
                'exports' => ['tea', 'coffee', 'plastics and packaging', 'pharmaceuticals'],
                'imports' => ['oilseeds', 'livestock products', 'textiles'],
                'agreements' => ['COMESA', 'African Union Trade Ministers engagement framework'],
                'orgs' => ['African Union Commission', 'Ethiopian Chamber of Commerce and Sectoral Associations'],
                'sectors' => ['AU multilateral engagement', 'coffee sector diplomacy'],
                'challenge' => null,
                'beats' => [
                    ['text' => 'Attended the African Union\'s Trade Ministers pre-summit consultations, supporting Kenya\'s delegation logistics in Addis Ababa.', 'type' => 'forum'],
                    ['text' => 'Facilitated a Kenyan plastics and packaging delegation\'s meetings with Ethiopian distributors.', 'type' => 'delegation'],
                    ['text' => 'Logged a currency-convertibility query affecting a Kenyan pharmaceuticals exporter\'s repatriation of proceeds from Ethiopian buyers.', 'type' => 'compliance'],
                    ['text' => 'Hosted the Ethiopian Chamber of Commerce and Sectoral Associations for a briefing on COMESA tariff harmonisation.', 'type' => 'forum'],
                    ['text' => 'Supported African Union Trade Ministers\' side-event logistics on continental coffee-sector cooperation.', 'type' => 'forum'],
                    ['text' => 'Facilitated Kenyan tea exporters\' participation in an Addis Ababa regional trade showcase.', 'type' => 'trade_show'],
                    ['text' => 'Resolved the currency-convertibility query through COMESA\'s regional payment and settlement system.', 'type' => 'compliance'],
                    ['text' => 'Hosted a Kenyan agro-processing delegation\'s meetings with African Union Commission trade policy officers.', 'type' => 'delegation'],
                    ['text' => 'Currently preparing briefing materials for the African Union\'s upcoming continental coffee-sector cooperation dialogue.', 'type' => 'other'],
                ],
            ],
        ];
    }

    /**
     * @return array{tier: string, primary_attache: string, junior_attaches: array<int, string>, exports: array<int, string>, imports: array<int, string>, agreements: array<int, string>, orgs: array<int, string>, sectors: array<int, string>, challenge: ?string, beats: array<int, array{text: string, type: string}>}
     */
    public static function forMission(string $missionName): array
    {
        return self::all()[$missionName]
            ?? throw new InvalidArgumentException("No trade profile authored for mission [{$missionName}].");
    }
}
